---
- name: Set up environment
  hosts: localhost
  become: true
  tasks:
    - name: Install packages
      apt:
        name:
          - docker.io
          - curl
          - jq
          - ca-certificates
        state: present
        update_cache: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Install Helm
      get_url:
        url: https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz
        dest: /tmp/helm.tar.gz

    - name: Extract and install Helm
      unarchive:
        src: /tmp/helm.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Install kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
